# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_executer'),
        ('application', '0002_auto_20180126_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('price', models.FloatField(blank=True, default=1.0, max_length=255, null=True, verbose_name='\u0411\u044e\u0434\u0436\u0435\u0442')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('number', models.CharField(max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('active', models.BooleanField(verbose_name='\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043e')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_executor_ready', to='main.Executer', verbose_name='\u0418\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories_ready', to='main.Subcategory', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043d\u0443\u044e \u0417\u0430\u044f\u0432\u043a\u0443',
                'verbose_name_plural': '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043d\u044b\u0435 \u0417\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u0441\u0435\u0440\u0432\u0438\u0441',
            },
        ),
    ]
