# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_readyapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readyapplication',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='readyapplication',
            name='subcategory',
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['active', 'timestamp'], 'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0443', 'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u0441\u0435\u0440\u0432\u0438\u0441'},
        ),
        migrations.DeleteModel(
            name='ReadyApplication',
        ),
    ]
