# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_executer'),
    ]

    operations = [
        migrations.AddField(
            model_name='executer',
            name='balance',
            field=models.FloatField(default=0, verbose_name='\u0411\u0430\u043b\u0430\u043d\u0441 \u0438\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044f'),
        ),
    ]
